import { useEffect, useRef, useState } from 'react';
import type { PunktGalerii } from '../../data/projectDetails';
import { Icon } from '../Icons';
export function GaleriaProjektu({ punkty }: { punkty:PunktGalerii[] }) {
  const [punkt, ustawPunkt] = useState(0); const [medium, ustawMedium] = useState(0); const [pelnyEkran, ustawPelnyEkran] = useState(false); const startX = useRef<number | null>(null); const wybrany = punkty[punkt]; const media = wybrany.media;
  const zmienMedium = (kierunek:number) => ustawMedium(obecny => (obecny + kierunek + media.length) % media.length);
  useEffect(() => { const obsluz = (zdarzenie:KeyboardEvent) => { const aktywny = document.activeElement?.tagName; if (aktywny === 'INPUT' || aktywny === 'TEXTAREA') return; if (zdarzenie.key === 'ArrowLeft') zmienMedium(-1); if (zdarzenie.key === 'ArrowRight') zmienMedium(1); if (zdarzenie.key === 'Escape') ustawPelnyEkran(false); }; window.addEventListener('keydown', obsluz); return () => window.removeEventListener('keydown', obsluz); });
  const wybierzPunkt = (indeks:number) => { ustawPunkt(indeks); ustawMedium(0); };
  const wybraneMedium = media[medium];
  return <div className="galeria-projektu"><div className="galeria-os" role="tablist" aria-label="Etapy galerii">{punkty.map((element, indeks) => <button type="button" role="tab" aria-selected={indeks === punkt} key={element.id} onClick={() => wybierzPunkt(indeks)}><img src={element.miniatura} alt=""/><span>{element.data}</span><b>{element.tytul}</b></button>)}</div><div className="galeria-karuzela" onPointerDown={zdarzenie => { startX.current = zdarzenie.clientX; }} onPointerUp={zdarzenie => { if (startX.current !== null && Math.abs(zdarzenie.clientX - startX.current) > 36) zmienMedium(zdarzenie.clientX < startX.current ? 1 : -1); startX.current = null; }}><button type="button" className="icon-button" aria-label="Poprzednie medium" onClick={() => zmienMedium(-1)}><Icon name="previous"/></button>{media.map((element, indeks) => <button type="button" key={element.id} className={indeks === medium ? 'aktywne' : ''} aria-label={`Wybierz medium ${indeks + 1}`} aria-pressed={indeks === medium} onClick={() => ustawMedium(indeks)}>{element.typ === 'image' ? <img src={element.url} alt={element.opis ?? ''}/> : <span>Film</span>}</button>)}<button type="button" className="icon-button" aria-label="Następne medium" onClick={() => zmienMedium(1)}><Icon name="next"/></button></div><div className="galeria-podglad">{wybraneMedium.typ === 'image' ? <img src={wybraneMedium.url} alt={wybraneMedium.opis ?? ''}/> : <video controls src={wybraneMedium.url}/>}<div><p>{wybraneMedium.opis}</p><button type="button" className="button secondary compact" onClick={() => ustawPelnyEkran(true)}><Icon name="fullscreen" size={15}/> Pełny ekran</button></div></div>{pelnyEkran && <dialog className="galeria-dialog" open onClick={() => ustawPelnyEkran(false)}><img src={wybraneMedium.url} alt={wybraneMedium.opis ?? ''}/><button type="button" className="button" onClick={() => ustawPelnyEkran(false)}>Zamknij</button></dialog>}</div>;
}