import { useState } from 'react';
import { contentItems, etykietyTypowTresci, poll } from '../data/siteData';
import { Icon } from '../components/Icons';
import { PanelPlanowaniaTresci } from '../moduly/tresci/PanelPlanowaniaTresci';
const Header=({kicker,title,desc}:{kicker:string,title:string,desc:string})=><div className="page-hero"><span className="section-kicker">{kicker}</span><h1>{title}</h1><p>{desc}</p></div>;
export function PollsPage(){const[voted,setVoted]=useState<number|null>(null);return <div className="page-wrap inner-page"><Header kicker="GŁOSOWANIA" title="Ty też możesz zdecydować." desc="Głosowania są miejscem, w którym społeczność pomaga ustalać kierunek kolejnych materiałów i projektów."/><div className="wide-card"><div className="card-topline"><span className="tag hot">AKTYWNE</span><span className="binding">Głosowanie niewiążące</span></div><h2>{poll.question}</h2><div className="vote-big-list">{poll.options.map((o,i)=><button key={o.label} className={voted===i?'selected':''} onClick={()=>setVoted(i)}><span>{String.fromCharCode(65+i)}</span><b>{o.label}</b>{voted===i&&<em>Twój wybór</em>}</button>)}</div><p className="demo-note">To działające głosowanie demonstracyjne. Wynik nie jest jeszcze zapisywany na serwerze.</p></div></div>}
export function ContentPage(){return <div className="page-wrap inner-page"><Header kicker="TREŚCI" title="Oglądaj, czytaj, pobieraj." desc="W jednym miejscu zbieram filmy, artykuły, aktualizacje projektów i materiały dodatkowe."/><div className="content-grid">{contentItems.map((item,i)=><article className="content-card" key={item.title}><div className={`content-thumb thumb-${i%4+1}`}><span>{item.tag}</span><div className="play-or-doc">{item.type==='video'?'▶':etykietyTypowTresci[item.type][0]}</div></div><div className="content-body"><span>{etykietyTypowTresci[item.type]}</span><h3>{item.title}</h3><p>{item.meta}</p></div></article>)}</div><PanelPlanowaniaTresci/></div>}
export function CommunityPage(){return <div className="page-wrap inner-page"><Header kicker="SPOŁECZNOŚĆ" title="Nie chcę budować tego w próżni." desc="Docelowo tutaj będą pomysły użytkowników, dyskusje, głosowania i miejsca do wspólnego rozwijania projektów."/><div className="three-cards"><article className="info-card"><Icon name="spark"/><h3>Pomysły</h3><p>Zgłaszaj propozycje materiałów i funkcji, które warto sprawdzić.</p></article><article className="info-card"><Icon name="vote"/><h3>Głosowania</h3><p>Pomagaj ustalać priorytety i wybierać kolejne kierunki rozwoju.</p></article><article className="info-card"><Icon name="people"/><h3>Profil społeczności</h3><p>Logowanie i profile użytkowników pojawią się w kolejnym etapie.</p></article></div></div>}
export function SupportPage(){return <div className="page-wrap inner-page"><Header kicker="WSPARCIE" title="Pomóż mi robić więcej i robić to lepiej." desc="Wersja MVP nie przyjmuje jeszcze płatności. Pokazuje jednak docelowy model wsparcia i sposób prezentowania wspierających."/><div className="support-options"><article className="support-card"><span>01</span><h3>Symboliczne wsparcie</h3><p>Drobne wsparcie pozwalające rozwijać narzędzia i opłacać infrastrukturę.</p><button disabled>Wkrótce</button></article><article className="support-card featured"><span>02</span><h3>Wspieram regularnie</h3><p>Dla osób, które chcą śledzić rozwój projektów i wcześniej oglądać część materiałów.</p><button disabled>Wkrótce</button></article><article className="support-card"><span>03</span><h3>Wsparcie projektu</h3><p>Możliwość wsparcia konkretnego projektu lub testu sprzętu.</p><button disabled>Wkrótce</button></article></div><div className="privacy-note"><Icon name="info"/><div><b>Widoczność pozostaje po Twojej stronie.</b><p>W przyszłości wspierający sam zdecyduje osobno, czy pokazać swój nick/nazwę oraz czy pokazać kwotę wsparcia.</p></div></div></div>}
export function CooperationPage(){return <div className="page-wrap inner-page"><Header kicker="WSPÓŁPRACA" title="Masz produkt, projekt albo pomysł? Porozmawiajmy." desc="Miejsce dla marek, twórców i firm zainteresowanych testami, materiałami, integracjami lub wspólnym projektem."/><div className="form-layout"><div className="three-stack"><article className="info-card"><h3>Testy i recenzje</h3><p>Sprzęt, akcesoria, aplikacje i narzędzia.</p></article><article className="info-card"><h3>Materiały partnerskie</h3><p>Współprace, które można jasno oznaczyć i zrobić uczciwie.</p></article><article className="info-card"><h3>Projekty technologiczne</h3><p>Integracje, prototypy i wspólne eksperymenty.</p></article></div><DemoForm title="Napisz w sprawie współpracy"/></div></div>}
export function AboutPage(){return <div className="page-wrap inner-page"><Header kicker="O KAPIM" title="Cześć, jestem Kapi." desc="Lubię rozkładać rzeczy na części, sprawdzać jak działają i budować rozwiązania, których sam potrzebuję."/><div className="about-grid"><div className="portrait-placeholder"><div>KA</div></div><div className="about-copy"><h2>Po Kapiemu znaczy: konkretnie, praktycznie i bez udawania.</h2><p>Ta strona powstaje jako centrum moich projektów, treści i eksperymentów. Nie chcę ograniczać jej do klasycznego portfolio — ma żyć razem z projektami i społecznością.</p><p>Znajdziesz tu m.in. narzędzia związane z wideo, automatyzacją pracy, testy sprzętu i materiały, które powstają po drodze.</p><div className="about-values"><span>Buduję</span><span>Testuję</span><span>Upraszczam</span><span>Pokazuję proces</span></div></div></div></div>}
function DemoForm({title}:{title:string}){const[sent,setSent]=useState(false);return <form className="contact-form" onSubmit={e=>{e.preventDefault();setSent(true)}}><h2>{title}</h2><label>Imię / firma<input required placeholder="Jak mam się do Ciebie zwracać?"/></label><label>E-mail<input required type="email" placeholder="kontakt@przyklad.pl"/></label><label>Temat<select><option>Współpraca</option><option>Pytanie</option><option>Projekt</option><option>Inne</option></select></label><label>Wiadomość<textarea required rows={6} placeholder="Napisz kilka słów..."/></label><button className="button primary" type="submit">Wyślij wiadomość <Icon name="arrow" size={16}/></button>{sent&&<div className="form-success">✓ Formularz działa. W MVP wiadomość nie jest jeszcze wysyłana na serwer.</div>}</form>}
export function ContactPage(){return <div className="page-wrap inner-page"><Header kicker="KONTAKT" title="Napisz. Najprościej jak się da." desc="Pytanie, pomysł, błąd na stronie albo temat do materiału — tutaj będzie główny punkt kontaktu."/><div className="form-layout"><div className="contact-aside"><div className="info-card"><Icon name="mail"/><h3>Formularz kontaktowy</h3><p>W tej wersji działa jako demonstracja interfejsu. Prawdziwa wysyłka zostanie podłączona przy backendzie.</p></div></div><DemoForm title="Wyślij wiadomość"/></div></div>}
