import { useState } from 'react';
import { Link } from 'react-router-dom';
import { etykietyTypowMaterialowRecenzenckich, reviews, type TypMaterialuRecenzenckiego } from '../data/siteData';
import { Icon } from '../components/Icons';
import { porownanieAdapterowUsbCJack } from '../moduly/porownania/daneAdapterowUsbCJack';

export function ReviewsHubPage() {
  const [tryb, ustawTryb] = useState<TypMaterialuRecenzenckiego>('review');
  const materialy = reviews.filter(recenzja => recenzja.typ === tryb);
  return <div className="page-wrap inner-page"><div className="page-hero"><span className="section-kicker">RECENZJE / TESTY / PORÓWNANIA</span><h1>Sprawdzam zamiast przepisywać specyfikację.</h1><p>Trzy formaty treści: werdykty o pojedynczych produktach, praktyczne testy oraz aktualizowane zestawienia porównawcze.</p></div><div className="segmented reviews-tabs" role="tablist" aria-label="Rodzaj materiału"><button role="tab" aria-selected={tryb === 'review'} className={tryb === 'review' ? 'active' : ''} onClick={() => ustawTryb('review')}>Recenzje</button><button role="tab" aria-selected={tryb === 'test'} className={tryb === 'test' ? 'active' : ''} onClick={() => ustawTryb('test')}>Testy</button><button role="tab" aria-selected={tryb === 'comparison'} className={tryb === 'comparison' ? 'active' : ''} onClick={() => ustawTryb('comparison')}>Porównania</button></div>{tryb !== 'comparison' ? <div className="reviews-grid large">{materialy.map(recenzja => <article className="review-card" key={recenzja.title}><div className="review-mark">{recenzja.title.slice(0,2).toUpperCase()}</div><div className="review-copy"><span>{etykietyTypowMaterialowRecenzenckich[recenzja.typ]}</span><h3>{recenzja.title}</h3><p>{recenzja.verdict}</p><small>{recenzja.author} · {recenzja.date}</small></div><div className="score"><strong>{recenzja.score}</strong><small>/10</small></div></article>)}</div> : <div className="comparison-grid">{materialy.map(recenzja => <article className="comparison-card" key={recenzja.title}><Icon name="reviews"/><h3>{recenzja.title}</h3><p>{recenzja.verdict}</p><small>{recenzja.author} · aktualizacja: {recenzja.date}</small><button className="button secondary compact" disabled>Tabela w przygotowaniu</button></article>)}<article className="comparison-card"><Icon name="reviews"/><h3>{porownanieAdapterowUsbCJack.nazwa}</h3><p>{porownanieAdapterowUsbCJack.opis}</p><Link className="button secondary compact" to={`/porownania/${porownanieAdapterowUsbCJack.slug}`}>Zobacz porównanie <Icon name="arrow" size={15}/></Link></article></div>}</div>;
}
