import { useState } from 'react';
import { reviews } from '../data/siteData';
import { Icon } from '../components/Icons';

type TrybRecenzji = 'reviews' | 'tests' | 'comparisons';

export function ReviewsHubPage() {
  const [tryb, ustawTryb] = useState<TrybRecenzji>('reviews');
  return <div className="page-wrap inner-page"><div className="page-hero"><span className="section-kicker">RECENZJE / TESTY / PORÓWNANIA</span><h1>Sprawdzam zamiast przepisywać specyfikację.</h1><p>Trzy formaty treści: werdykty o pojedynczych produktach, praktyczne testy oraz aktualizowane zestawienia porównawcze.</p></div><div className="segmented reviews-tabs" role="tablist" aria-label="Rodzaj materiału"><button role="tab" aria-selected={tryb === 'reviews'} className={tryb === 'reviews' ? 'active' : ''} onClick={() => ustawTryb('reviews')}>Recenzje</button><button role="tab" aria-selected={tryb === 'tests'} className={tryb === 'tests' ? 'active' : ''} onClick={() => ustawTryb('tests')}>Testy</button><button role="tab" aria-selected={tryb === 'comparisons'} className={tryb === 'comparisons' ? 'active' : ''} onClick={() => ustawTryb('comparisons')}>Porównania</button></div>{tryb !== 'comparisons' ? <div className="reviews-grid large">{reviews.filter((_,indeks) => tryb === 'reviews' ? indeks !== 1 : indeks === 1).map(recenzja => <article className="review-card" key={recenzja.title}><div className="review-mark">{recenzja.title.slice(0,2).toUpperCase()}</div><div className="review-copy"><span>{tryb === 'reviews' ? 'Recenzja' : 'Test praktyczny'}</span><h3>{recenzja.title}</h3><p>{recenzja.verdict}</p><small>{recenzja.author} · {recenzja.date}</small></div><div className="score"><strong>{recenzja.score}</strong><small>/10</small></div></article>)}</div> : <div className="comparison-grid"><article className="comparison-card"><Icon name="reviews"/><h3>Przenośne DAC-i USB-C</h3><p>Porównanie mocy, poboru energii, funkcji i opłacalności małych przetworników.</p><small>8 produktów · aktualizacja: lipiec 2026</small><button className="button secondary compact" disabled>Tabela w przygotowaniu</button></article><article className="comparison-card"><Icon name="reviews"/><h3>Programy do montażu</h3><p>Stale rozwijane zestawienie funkcji, wydajności i kosztów popularnych edytorów.</p><small>6 produktów · aktualizacja: czerwiec 2026</small><button className="button secondary compact" disabled>Tabela w przygotowaniu</button></article></div>}</div>;
}
